% This executive script is perform quick testing of Matlab Report Functions
% Created: Jan 11,2021
% Written By: Stephen Forczyk
% Revised:

%
% Classification: Unclassified/Public Domain
global Datasets FlagSelections2 FlagSelections;
global BandDataS MetaDataS;
global CMIS DQFS tS yS xS tBS goesImagerS yImgS yImgBS;
global xImgS xImgBS SatDataS GeoSpatialS;
global ReflectanceS AlgoS ErrorS EarthSunS VersionContainerS;
global GoesWaveBand GoesWaveBand2 GoesWaveBandTable ESunS kappa0S PlanckS FocalPlaneS;
global GOESFileName MapFormFactor;
global GOES16BandPaths;
global isaveGOESLightningData isaveCMI;
global CountyBoundaryFile;
global CountyBoundaries StateFIPSFile;
global StateFIPSCodes NationalCountiesShp;
global USAStatesShapeFileList USAStatesFileName;
global UrbanAreasShapeFile NorthAmericaLakes FireSummaryFile;
global idebug isavefiles;
global iPrimeRoads iCountyRoads iCommonRoads iStateRecRoads iUSRoads iStateRoads;
global iLakes;
global NumProcFiles ProcFileList;
global RptGenPresent iCreatePDFReport pdffilename rpt chapter;
global JpegCounter JpegFileList;

global fid;
global widd2 lend2;
global initialtimestr igrid ijpeg ilog imovie;
global vert1 hor1 widd lend;


global vert2 hor2 machine;
global chart_time;
global Fz1 Fz2;
global idirector mov izoom iwindow;
global matpath GOES16path;
global jpegpath tiffpath;
global smhrpath excelpath ascpath;
global ipowerpoint PowerPointFile scaling stretching padding;
global ichartnum;
global ColorList RGBVals ColorList2 xkcdVals LandColors;
global orange bubblegum brown brightblue;
% additional paths needed for mapping
global matpath1 mappath matlabpath;
global jpegpath northamericalakespath logpath pdfpath govjpegpath;
global GOES16Band1path GOES16Band2path GOES16Band3path GOES16Band4path;
global GOES16Band5path GOES16Band6path GOES16Band7path GOES16Band8path
global GOES16Band9path GOES16Band10path GOES16Band11path GOES16Band12path;
global GOES16Band13path GOES16Band14path GOES16Band15path GOES16Band16path;
global GOES16CloudTopHeightpath GOES16CloudTopTemppath GOES16Lightningpath;
global GOES16ConusBand1path shapefilepath Countryshapepath figpath;
global mappath gridpath countyshapepath nationalshapepath summarypath;
global DayMonthNonLeapYear DayMonthLeapYear CalendarFileName;

% Set some flags to control program execution
isaveGOESLightningData=0;
isaveCMI=0;
idebug=1;
isavefiles=0;
iCreatePDFReport=1;
JpegCounter=0;
clc;
% Set up some fixed paths for the data
mappath='D:\Forczyk\Map_Data\Matlab_Maps\';
matlabpath='D:\Goes16\Matlab_Data\';
CalendarFileName='CalendarDays.mat';
shapefilepath='D:\Goes16\ShapeFiles\';
countyshapepath='D:\Forczyk\Map_Data\MAT_Files_Geographic\';
CountyBoundaryFile='CountyBoundingBoxes';
nationalshapepath='D:\Forczyk\Map_Data\NationalShapeFiles\';
NationalCountiesShp='cb_2018_us_county_500k.shp';
UrbanAreasShapeFile='cb_2018_us_ua10M_500k.shp';
USAStatesFileName='USAStatesShapeFileMapListRev4.mat';
northamericalakespath='D:\Forczyk\Map_Data\Natural_Earth\Ten_Meter_Physical\';
NorthAmericaLakes='ne_10m_lakes_north_america.shp';
GOES16path='D:\Goes16\Imagery\July25_2020\Band01\';
GOES16Lightningpath='D:\Goes16\All_Other_Data\GLM_L2_Lightning_Detection\';
jpegpath='D:\Goes16\Imagery\Sept12_2020\Jpeg_Files\';
pdfpath='D:\Goes16\Imagery\Sept12_2020\PDF_Files\';
govjpegpath='D:\Goes16\Documents\Jpeg\';
figpath='D:\Goes16\Imagery\Oct_FigFiles\';
logpath='D:\Goes16\Log_Files\';
summarypath='D:\Goes16\Summary_Files\';
tiffpath='D:\Forczyk\Map_Data\InterstateSigns\';
FireSummaryFile='SummaryFileData.mat';
GOES16BandPaths=cell(1,1);
GOES16BandPaths{1,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band01\';
GOES16BandPaths{2,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band02\';
GOES16BandPaths{3,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band03\';
GOES16BandPaths{4,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band04\';
GOES16BandPaths{5,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band05\';
GOES16BandPaths{6,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band06\';
GOES16BandPaths{7,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band07\';
GOES16BandPaths{8,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band08\';
GOES16BandPaths{9,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band09\';
GOES16BandPaths{10,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band10\';
GOES16BandPaths{11,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band11\';
GOES16BandPaths{12,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band12\';
GOES16BandPaths{13,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band13\';
GOES16BandPaths{14,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band14\';
GOES16BandPaths{15,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band15\';
GOES16BandPaths{16,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L2_Cloud_Moisture\Conus\Band16\';
GOES16BandPaths{17,1}='D:\Goes16\All_Other_Data\CONUS_Cloud_Top_Heights\July25_2020\';
GOES16BandPaths{18,1}='D:\Goes16\Imagery\Aug26_2020\FullDisk_Cloud_Top_Temp\';
GOES16BandPaths{19,1}='D:\Goes16\Imagery\Aug26_2020\CONUS_GLM_Flash_Data\';
GOES16BandPaths{20,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band01\';
GOES16BandPaths{21,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band02\';
GOES16BandPaths{22,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band03\';
GOES16BandPaths{23,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band04\';
GOES16BandPaths{24,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band05\';
GOES16BandPaths{25,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band06\';
GOES16BandPaths{26,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band07\';
GOES16BandPaths{27,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band08\';
GOES16BandPaths{28,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band09\';
GOES16BandPaths{29,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band10\';
GOES16BandPaths{30,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band11\';
GOES16BandPaths{31,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band12\';
GOES16BandPaths{32,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band13\';
GOES16BandPaths{33,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band14\';
GOES16BandPaths{34,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band15\';
GOES16BandPaths{35,1}='D:\Goes16\Imagery\Aug26_2020\ABI_L1_Radiances\Conus\Band16\';
GOES16BandPaths{36,1}='D:\Goes16\CONUS_Images\July25_2020\MultiBand\';
GOES16BandPaths{37,1}='D:\Goes16\MesoScale1\July25_2020\Band01\';
GOES16BandPaths{38,1}='D:\Goes16\MesoScale1\July25_2020\Band02\';
GOES16BandPaths{39,1}='D:\Goes16\MesoScale1\July25_2020\Band03\';
GOES16BandPaths{40,1}='D:\Goes16\MesoScale1\July25_2020\Band04\';
GOES16BandPaths{41,1}='D:\Goes16\MesoScale1\July25_2020\Band05\';
GOES16BandPaths{42,1}='D:\Goes16\MesoScale1\July25_2020\Band06\';
GOES16BandPaths{43,1}='D:\Goes16\MesoScale1\July25_2020\Band07\';
GOES16BandPaths{44,1}='D:\Goes16\MesoScale1\July25_2020\Band08\';
GOES16BandPaths{45,1}='D:\Goes16\MesoScale1\July25_2020\Band09\';
GOES16BandPaths{46,1}='D:\Goes16\MesoScale1\July25_2020\Band10\';
GOES16BandPaths{47,1}='D:\Goes16\MesoScale1\July25_2020\Band11\';
GOES16BandPaths{48,1}='D:\Goes16\Imagery\Aug26_2020\MultiBand_CONUS\';
GOES16BandPaths{49,1}='D:\Goes16\Forczyk_Python\';
GOES16BandPaths{50,1}='D:\Goes16\Imagery\Aug26_2020\MultiBand_FullDisk\';
GOES16BandPaths{51,1}='D:\Goes16\Imagery\Aug26_2020\CONUS_Cloud_Top_Heights\';
GOES16BandPaths{52,1}='D:\Goes16\Imagery\Aug26_2020\FullDisk_Cloud_Top_Heights\';
GOES16BandPaths{53,1}='D:\Goes16\Imagery\Sept12_2020\ABI_L2_Fire\';
GOES16BandPaths{54,1}='D:\Goes16\Imagery\Aug26_2020\CONUS_Derived_Motion_Winds\';
GOES16BandPaths{55,1}='D:\Goes16\Imagery\Aug26_2020\CONUS_Cloud_Top_Pressure\';
GOES16BandPaths{56,1}='D:\Goes16\Imagery\Aug26_2020\FullDisk_Cloud_Top_Temp\';
GOES16BandPaths{57,1}='D:\Goes16\Imagery\Aug26_2020\CONUS_Clear_Sky_Mask\';
GOES16BandPaths{58,1}='D:\Goes16\Imagery\Aug26_2020\FullDisk_SeaSurface_Temp\';
GOES16BandPaths{59,1}='D:\Goes16\Imagery\Aug26_2020\CONUS_ABI_L2_LandSurface_Temp\';
GOES16Band1path='D:\Goes16\Imagery\July25_2020\Band01\';
GOES16Band2path='D:\Goes16\Imagery\July25_2020\Band02\';
GOES16Band3path='D:\Goes16\Imagery\July25_2020\Band03\';
GOES16Band4path='D:\Goes16\Imagery\July25_2020\Band04\';
GOES16Band5path='D:\Goes16\Imagery\July25_2020\Band05\';
GOES16Band6path='D:\Goes16\Imagery\July25_2020\Band06\';
GOES16Band7path='D:\Goes16\Imagery\July25_2020\Band07\';
GOES16Band8path='D:\Goes16\Imagery\July25_2020\Band08\';
GOES16Band9path='D:\Goes16\Imagery\July25_2020\Band09\';
GOES16Band10path='D:\Goes16\Imagery\July25_2020\Band10\';
GOES16Band11path='D:\Goes16\Imagery\July25_2020\Band11\';
GOES16Band12path='D:\Goes16\Imagery\July25_2020\Band12\';
GOES16Band13path='D:\Goes16\Imagery\July25_2020\Band13\';
GOES16Band14path='D:\Goes16\Imagery\July25_2020\Band14\';
GOES16Band15path='D:\Goes16\Imagery\July25_2020\Band15\';
GOES16Band16path='D:\Goes16\Imagery\July25_2020\Band16\';
GOES16CloudTopHeightpath='D:\Goes16\All_Other_Data\CONUS_Cloud_Top_Heights\July25_2020\';
GOES16CloudTopTemppath='D:\Goes16\All_Other_Data\ABI_L2_Cloud_Top_Temperature\';
matpath=GOES16path;
Countryshapepath='D:\Forczyk\Map_Data\CountryShapefiles\';
gridpath='D:\Goes16\Grids\';
MapFormFactor=[];
Datasets=cell(1,1);
Datasets{1,1}='ABI-L2-CMI-Imagery-Band-1*R';
Datasets{2,1}='ABI-L2-CMI-Imagery-Band-2*R';
Datasets{3,1}='ABI-L2-CMI-Imagery-Band-3*R';
Datasets{4,1}='ABI-L2-CMI-Imagery-Band-4*R';
Datasets{5,1}='ABI-L2-CMI-Imagery-Band-5*R';
Datasets{6,1}='ABI-L2-CMI-Imagery-Band-6*R';
Datasets{7,1}='ABI-L2-CMI-Imagery-Band-7*R';
Datasets{8,1}='ABI-L2-CMI-Imagery-Band-8*R';
Datasets{9,1}='ABI-L2-CMI-Imagery-Band-9*R';
Datasets{10,1}='ABI-L2-CMI-Imagery-Band-10*R';
Datasets{11,1}='ABI-L2-CMI-Imagery-Band-11*R';
Datasets{12,1}='ABI-L2-CMI-Imagery-Band-12*R';
Datasets{13,1}='ABI-L2-CMI-Imagery-Band-13*R';
Datasets{14,1}='ABI-L2-CMI-Imagery-Band-14*R';
Datasets{15,1}='ABI-L2-CMI-Imagery-Band-15*R';
Datasets{16,1}='ABI-L2-CMI-Imagery-Band-16*R';
Datasets{17,1}='Do Not Use';
Datasets{18,1}='FullDisk-ABI-Cloud Top Temperature*R';
Datasets{19,1}='CONUS-GLM-L2_Lightning*';
Datasets{20,1}='CONUS-ABI-L1-Radiance-Band-1*';
Datasets{21,1}='CONUS-ABI-L1-Radiance-Band-2*';
Datasets{22,1}='CONUS-ABI-L1-Radiance-Band-3*';
Datasets{23,1}='CONUS-ABI-L1-Radiance-Band-4*';
Datasets{24,1}='CONUS-ABI-L1-Radiance-Band-5*';
Datasets{25,1}='CONUS-ABI-L1-Radiance-Band-6*';
Datasets{26,1}='CONUS-ABI-L1-Radiance-Band-7*';
Datasets{27,1}='CONUS-ABI-L1-Radiance-Band-8*';
Datasets{28,1}='CONUS-ABI-L1-Radiance-Band-9*';
Datasets{29,1}='CONUS-ABI-L1-Radiance-Band-10*';
Datasets{30,1}='CONUS-ABI-L1-Radiance-Band-11*';
Datasets{31,1}='CONUS-ABI-L1-Radiance-Band-12*';
Datasets{32,1}='CONUS-ABI-L1-Radiance-Band-13*';
Datasets{33,1}='CONUS-ABI-L1-Radiance-Band-14*';
Datasets{34,1}='CONUS-ABI-L1-Radiance-Band-15*';
Datasets{35,1}='CONUS-ABI-L1-Radiance-Band-16*';
Datasets{36,1}='Do not Use';
Datasets{37,1}='MesoScale1-ABI-L2-Imagery-Band01';
Datasets{38,1}='MesoScale1-ABI-L2-Imagery-Band02';
Datasets{39,1}='MesoScale1-ABI-L2-Imagery-Band03';
Datasets{40,1}='MesoScale1-ABI-L2-Imagery-Band04';
Datasets{41,1}='MesoScale1-ABI-L2-Imagery-Band05';
Datasets{42,1}='MesoScale1-ABI-L2-Imagery-Band06';
Datasets{43,1}='MesoScale1-ABI-L2-Imagery-Band07';
Datasets{44,1}='MesoScale1-ABI-L2-Imagery-Band08';
Datasets{45,1}='MesoScale1-ABI-L2-Imagery-Band09';
Datasets{46,1}='MesoScale1-ABI-L2-Imagery-Band10';
Datasets{47,1}='MesoScale1-ABI-L2-Imagery-Band11';
Datasets{48,1}='CONUS-ABI-L2-Imagery-Multiband*R';
Datasets{49,1}='GEOS-Lat-Lon-CONUS-Grid';
Datasets{50,1}='FullDisk-ABI-L2-Imagery-Multiband*R';
Datasets{51,1}='CONUS-Cloud-Top-Heights*R';
Datasets{52,1}='FullDisk-Cloud-Top-Heights*R';
Datasets{53,1}='ABI-L2-Fire*';
Datasets{54,1}='CONUS-Winds';
Datasets{55,1}='CONUSCloudTopPressure*';
Datasets{56,1}='Do Not Use';
Datasets{57,1}='CONUS-ClearSky-Mask*';
Datasets{58,1}='FullDisk-SeaSurfaceTemp*';
Datasets{59,1}='Conus-LandSurfaceTemp*';
Datasets{60,1}='STOP RUN';
% Set up some initial data
ProcFileList=cell(1,3);
ProcFileList{1,1}='File Type';
ProcFileList{1,2}='File Name';
ProcFileList{1,3}='Source Directory';
JpegFileList=cell(1,2);
JpegFileList{1,1}='Source Directory';
JpegFileList{1,2}='JPegFileName';
% Set up cell to hold generic GOES Waveband Data
GoesWaveBand=cell(17,5);
GoesWaveBand{1,1}='Band Num';
GoesWaveBand{1,2}='Resolution-km';
GoesWaveBand{1,3}='Wavelength-microns';
GoesWaveBand{1,4}='Spectrum';
GoesWaveBand{1,5}='Band Desc';
GoesWaveBand{2,1}=1;
GoesWaveBand{2,2}=1;
GoesWaveBand{2,3}=0.47;
GoesWaveBand{2,4}='Visible';
GoesWaveBand{2,5}='Blue Band';
GoesWaveBand{3,1}=2;
GoesWaveBand{3,2}=0.5;
GoesWaveBand{3,3}=0.64;
GoesWaveBand{3,4}='Visible';
GoesWaveBand{3,5}='Red Band';
GoesWaveBand{4,1}=3;
GoesWaveBand{4,2}=1;
GoesWaveBand{4,3}=0.86;
GoesWaveBand{4,4}='Near IR';
GoesWaveBand{4,5}='Red Band';
GoesWaveBand{5,1}=4;
GoesWaveBand{5,2}=2;
GoesWaveBand{5,3}=1.37;
GoesWaveBand{5,4}='Near-IR';
GoesWaveBand{5,5}='Cirrus Band';
GoesWaveBand{6,1}=5;
GoesWaveBand{6,2}=1;
GoesWaveBand{6,3}=1.60;
GoesWaveBand{6,4}='Near-IR';
GoesWaveBand{6,5}='Snow/Ice Band';
GoesWaveBand{7,1}=6;
GoesWaveBand{7,2}=2;
GoesWaveBand{7,3}=2.24;
GoesWaveBand{7,4}='Near-IR';
GoesWaveBand{7,5}='Cloud Particle Band';
GoesWaveBand{8,1}=7;
GoesWaveBand{8,2}=2;
GoesWaveBand{8,3}=3.90;
GoesWaveBand{8,4}='IR';
GoesWaveBand{8,5}='Short Wave Window Band';
GoesWaveBand{9,1}=8;
GoesWaveBand{9,2}=2;
GoesWaveBand{9,3}=6.20;
GoesWaveBand{9,4}='IR';
GoesWaveBand{9,5}='Upper Troposphere WV Band';
GoesWaveBand{10,1}=9;
GoesWaveBand{10,2}=2;
GoesWaveBand{10,3}=6.90;
GoesWaveBand{10,4}='IR';
GoesWaveBand{10,5}='Mid Level Troposphere WV Band';
GoesWaveBand{11,1}=10;
GoesWaveBand{11,2}=2;
GoesWaveBand{11,3}=7.30;
GoesWaveBand{11,4}='IR';
GoesWaveBand{11,5}='Low Level Troposphere WV Band';
GoesWaveBand{12,1}=11;
GoesWaveBand{12,2}=2;
GoesWaveBand{12,3}=8.40;
GoesWaveBand{12,4}='IR';
GoesWaveBand{12,5}='Cloud Top Phase Band';
GoesWaveBand{13,1}=12;
GoesWaveBand{13,2}=2;
GoesWaveBand{13,3}=9.60;
GoesWaveBand{13,4}='IR';
GoesWaveBand{13,5}='Ozone Band';
GoesWaveBand{14,1}=13;
GoesWaveBand{14,2}=2;
GoesWaveBand{14,3}=10.30;
GoesWaveBand{14,4}='IR';
GoesWaveBand{14,5}='Clean IR Longwave Band';
GoesWaveBand{15,1}=14;
GoesWaveBand{15,2}=2;
GoesWaveBand{15,3}=11.20;
GoesWaveBand{15,4}='IR';
GoesWaveBand{15,5}='IR Longwave Band';
GoesWaveBand{16,1}=15;
GoesWaveBand{16,2}=2;
GoesWaveBand{16,3}=12.30;
GoesWaveBand{16,4}='IR';
GoesWaveBand{16,5}='Dirty IR Longwave Band';
GoesWaveBand{17,1}=16;
GoesWaveBand{17,2}=2;
GoesWaveBand{17,3}=13.30;
GoesWaveBand{17,4}='IR';
GoesWaveBand{17,5}='CO2 IR Longwave Band';
GoesWaveBand2=cell(16,5);
for j=2:17
    for k=1:5
        if(k~=3)
            GoesWaveBand2{j-1,k}=GoesWaveBand{j,k};
        else
            nowVal=GoesWaveBand{j,k};
            nowStr=num2str(nowVal,2);
            GoesWaveBand2{j-1,k}=nowStr;
        end
    end
end
GoesWaveBandTable=cell2table(GoesWaveBand2,...
    'VariableNames',{'Band Num' 'Resolution-Km' 'Wavelength-microns' 'Spectrum' 'Band Desc'});
toolbox='MATLAB Report Generator';
[RptGenPresent] = ToolboxChecker(toolbox);
% Start writing a log file
eval(['cd ' logpath(1:length(logpath)-1)]);
startruntime=deblank(datestr(now));
startrunstr=strcat('Start Run GOES 16 Run at-',startruntime);
logfilename=startruntime;
logfiledbl=double(logfilename);
% find the blank space in the date and replace it with a '-' to make a
% legalfilename
[iblank]=find(logfiledbl==32);
numblank=length(iblank);
for n=1:numblank
    is=iblank(n);
    ie=is;
    logfilename(is:ie)='-';
end
[icolon]=strfind(logfilename,':');
numcolon=length(icolon);
for n=1:numcolon
    is=icolon(n);
    ie=is;
    logfilename(is:ie)='-';
end
datetimestr=logfilename;
logfilename=strcat('LogFile-',logfilename,'.txt');
pdffilename=strcat('GOES16-',datetimestr);
fid=fopen(logfilename,'w');
dispstr=strcat('Opened Log file-',logfilename,'-for writing');
disp(dispstr);
fprintf(fid,'%50s\n',startrunstr);

% Create a PDF Report Using the Matab Report Generator is requested
if((iCreatePDFReport==1) && (RptGenPresent==1))
    import mlreportgen.dom.*;
    import mlreportgen.report.*;
    import mlreportgen.utils.*
    CreatePDFReportHeader
else
    fprintf(fid,'%s\n','No PDF report will be created for this run');
end
eval(['cd ' jpegpath(1:length(jpegpath)-1)]);
% Create Some Input based on the Fire Data
GOESShortFileName ='OR_ABI-L2-FDCC-M6_G16_s20202561616157';
figstr2 ='Louisiana-StateLevelFireHotSpotTemps-s20202561616157.jpg';
ab=1;
if((iCreatePDFReport==1) && (RptGenPresent==1))
%     [ibreak]=strfind(GOESFileName,'_e');
%     is=1;
%     ie=ibreak(1)-1;
%     GOESShortFileName=GOESFileName(is:ie);
    headingstr1=strcat('Hot Spot From File-',GOESShortFileName);
    chapter = Chapter("Title",headingstr1);
    imdata = imread(figstr2);
    [nhigh,nwid,ndepth]=size(imdata);
    image = mlreportgen.report.FormalImage();
    image.Image = which(figstr2);
    pdftxtstr=strcat('Hot Spots For File-',GOESShortFileName);
    pdftext = Text(pdftxtstr);
    pdftext.Color = 'red';
    image.Caption = pdftext;
    nhighs=floor(nhigh/2.4);
    nwids=floor(nwid/2.4);
    heightstr=strcat(num2str(nhighs),'px');
    widthstr=strcat(num2str(nwids),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image);
    parastr10='The Data for this chart was from file-';
    parastr11=strcat(parastr10,GOESFileName,'.');
    parastr12=strcat(parastr10,parastr11);
    p4 = Paragraph(parastr12);
    p4.Style = {OuterMargin("0pt", "0pt","0pt","10pt")};
    add(chapter,p4);
    FireState='California';
    FireCounty='RedNeck';
    TempC=520.0;
    iBullsEye=3;
    iBullsEyeInc=20;
    parastr13='The data plotted on this chart depicts a single, user selected "Hot Spot" on a state level map.';
    parastr14=strcat('The user selected fire is in the state of-',FireState,'-and County of-',FireCounty,'-with a max temp of-',...
        num2str(TempC,6),'-Deg-k.');
    parastr15='This map is feature rich in order to allow the user to see the location of hot spots in relation to signigficant geographic features.';
    parastr16='For example, the map displays the selected state with the individual counties color-coded for clarity.';
    parastr17='The user does have some control of the features to be plotted such as roads,river,lakes and cities.';
    parastr18='This feature was added because plotting all these items is quite time consuming so the user can selectively turn some features off.';
    parastr19='The actual hot spot detected by GOES is identified by a colored dot at the fire center and a set of concentric bullseye rings to provide a distance scale.';
    parastr20=strcat('The size of the bullseye is dependent on the latitude extent of the state,in this example there are-',num2str(iBullsEye),'-rings spaced-',...
        num2str(iBullsEyeInc),'-km apart.');
    parastr21=strcat(parastr13,parastr14,parastr15,parastr16,parastr17,parastr18,parastr19,parastr20);
    p5 = Paragraph(parastr21);
    p5.Style = {OuterMargin("0pt", "0pt","0pt","10pt")};
    add(chapter,p5);
FlagSelections=cell(6,4);
FlagSelections{1,1}='iPrimeRoads';
FlagSelections{1,2}=iPrimeRoads;
FlagSelections{1,3}='Plot Interstates';
FlagSelections{1,4}='All Up To 200';
FlagSelections{2,1}='iCountyRoads';
FlagSelections{2,2}=iCountyRoads';
FlagSelections{2,3}='Plot County Roads';
FlagSelections{2,4}='0 For this Map';
FlagSelections{3,1}='iCommonRoads';
FlagSelections{3,2}=iCommonRoads;
FlagSelections{3,3}='Plot Common Roads';
FlagSelections{3,4}='0 For this Map';
FlagSelections{4,1}='iStateRecRoads';
FlagSelections{4,2}=iStateRecRoads;
FlagSelections{4,3}='Plot State Recognized Roads';
FlagSelections{4,4}='0 For this Map';
FlagSelections{5,1}='iUSRoads';
FlagSelections{5,2}=iUSRoads;
FlagSelections{5,3}='Plot Other State Roads';
FlagSelections{5,4}='0 For this Map';
FlagSelections{6,1}='iStateRoads';
FlagSelections{6,2}=iStateRoads;
FlagSelections{6,3}='Plot State Roads';
FlagSelections{6,4}='All Up To 100';
FlagSelections2=cell(7,4);
FlagSelections2{1,1}='Flag';
FlagSelections2{1,2}='Variable';
FlagSelections2{1,3}='Purpose';
FlagSelections2{1,4}='Purpose';
FlagSelections2{2,1}='iPrimeRoads';
FlagSelections2{2,2}=iPrimeRoads;
FlagSelections2{2,3}='Plot Interstates';
FlagSelections2{2,4}='All Up To 200';
FlagSelections2{3,1}='iCountyRoads';
FlagSelections2{3,2}=iCountyRoads';
FlagSelections2{3,3}='Plot County Roads';
FlagSelections2{3,4}='0 For this Map';
FlagSelections2{4,1}='iCommonRoads';
FlagSelections2{4,2}=iCommonRoads;
FlagSelections2{4,3}='Plot Common Roads';
FlagSelections2{4,4}='0 For this Map';
FlagSelections2{5,1}='iStateRecRoads';
FlagSelections2{5,2}=iStateRecRoads;
FlagSelections2{5,3}='Plot State Recognized Roads';
FlagSelections2{5,4}='0 For this Map';
FlagSelections2{6,1}='iUSRoads';
FlagSelections2{6,2}=iUSRoads;
FlagSelections2{6,3}='Plot Other State Roads';
FlagSelections2{6,4}='0 For this Map';
FlagSelections2{7,1}='iStateRoads';
FlagSelections2{7,2}=iStateRoads;
FlagSelections2{7,3}='Plot State Roads';
FlagSelections2{7,4}='All Up To 100';
tbl_header2 = {'Flag' 'Variable' 'Purpose' 'Limits'};
T2=cell2table(FlagSelections,'VariableNames',{'Flag' 'Variable' 'Purpose' 'Limits'});
% T2.Style = [table.Style {Border('inset','red','3px'), ...
%                ColSep('single','black','1px'), ...
%                RowSep('single','black','1px')}];
% 
% T2.BackgroundColor = 'lightsteelblue';
T3=cell2table(FlagSelections2);
%bt2=BaseTable(T2);
%bt2.TableStyleName="smfdefault.pdftx";
bt = BaseTable(T3);
tabletitle = Text('State Level Plot Flags');
tabletitle.Bold = false;
bt.Title = tabletitle;
bt.TableWidth="7in";
%bt2.Title=tabletitle;
%bt2.TableWidth="7in";

%mltableObj = MATLABTable(T2);
add(chapter,bt);
add(rpt,chapter);
end
close(rpt);
rptview(rpt);